### ISSUE TITLE
Add crypto2stix for `pattern_cryptocurrency_btc_transaction` pattern extraction

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/txt2stix#12]
https://github.com/muchdogesec/txt2stix/tree/main/docs#stix-mapping-cryptocurrency-transaction

Test 

```shell
python3 txt2stix.py \
	--relationship_mode standard \
	--input_file tests/inputs/extraction_types/generic_cryptocurrency_btc_transaction.txt \
	--name 'Test 3.1.31.3 pattern_cryptocurrency_btc_transaction' \
	--tlp_level clear \
	--confidence 100 \
	--use_extractions pattern_cryptocurrency_btc_transaction
```

**Comment by himynamesdave** [comment]
blocked by #20

**Comment by himynamesdave** [comment]
```
python3 txt2stix.py \
	--relationship_mode standard \
	--input_file tests/inputs/extraction_types/generic_cryptocurrency_btc_transaction.txt \
	--name 'Test 3.1.31.3 pattern_cryptocurrency_btc_transaction' \
	--tlp_level clear \
	--confidence 100 \
	--use_extractions pattern_cryptocurrency_btc_transaction
```

```
04-Aug-24 09:31:17 [txt2stix] [INFO] Saving log to `/Users/dgreenwood/Documents/repos/dogesec/txt2stix/logs/logs-5bf3d211-9abd-47db-a03c-36485e2c0b76.log`
04-Aug-24 09:31:17 [txt2stix] [INFO] =====================txt2stix======================
04-Aug-24 09:31:17 [txt2stix] [INFO] Arguments: ["--relationship_mode", "standard", "--input_file", "tests/inputs/extraction_types/generic_cryptocurrency_btc_transaction.txt", "--name", "Test 3.1.31.3 pattern_cryptocurrency_btc_transaction", "--tlp_level", "clear", "--confidence", "100", "--use_extractions", "pattern_cryptocurrency_btc_transaction"]
04-Aug-24 09:31:17 [txt2stix] [INFO] using pattern extractors
04-Aug-24 09:31:17 [txt2stix] [INFO] using pattern extractors
04-Aug-24 09:31:18 [txt2stix] [ERROR] ran into exception while processing observable `{'value': '8691f4cac0542ed1d1ae6c47bd5926e39d7911d9148e6ef64060c6ff5e245898', 'type': 'pattern_cryptocurrency_btc_transaction', 'version': '1.0.0', 'stix_mapping': 'cryptocurrency-transaction', 'start_index': [13], 'id': 'ex_0'}`
Traceback (most recent call last):
  File "/Users/dgreenwood/Documents/repos/dogesec/txt2stix/txt2stix/stix.py", line 411, in process_observables
    self.add_indicator(ex, add_standard_relationship)
  File "/Users/dgreenwood/Documents/repos/dogesec/txt2stix/txt2stix/stix.py", line 339, in add_indicator
    objects, related_refs = build_observables(
                            ^^^^^^^^^^^^^^^^^^
  File "/Users/dgreenwood/Documents/repos/dogesec/txt2stix/txt2stix/indicator.py", line 349, in build_observables
    txn_object, *other_objects = btc2stix.process_transaction(value)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dgreenwood/Documents/repos/dogesec/txt2stix/txt2stix-venv/lib/python3.11/site-packages/stix2extensions/tools/crypto2stix.py", line 98, in process_transaction
    tx_data = self.get_transaction_data(txn)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dgreenwood/Documents/repos/dogesec/txt2stix/txt2stix-venv/lib/python3.11/site-packages/stix2extensions/tools/crypto2stix.py", line 158, in get_transaction_data
    hash=txn['hash'],
         ~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'
Stack (most recent call last):
  File "/Users/dgreenwood/Documents/repos/dogesec/txt2stix/txt2stix.py", line 3, in <module>
    main()
  File "/Users/dgreenwood/Documents/repos/dogesec/txt2stix/txt2stix/txt2stix.py", line 214, in main
    all_extracts = extract_all(bundler, args.use_extractions, aliased_input, ai_extractor=ai_extractor_session)
  File "/Users/dgreenwood/Documents/repos/dogesec/txt2stix/txt2stix/txt2stix.py", line 161, in extract_all
    bundler.process_observables(pattern_extracts)
  File "/Users/dgreenwood/Documents/repos/dogesec/txt2stix/txt2stix/stix.py", line 413, in process_observables
    logger.exception(
04-Aug-24 09:31:18 [txt2stix] [INFO] Writing bundle output to `output/bundle--14b21405-ffd5-5a79-99da-99c06e2d9d41.json`
```

**Comment by fqrious** [comment]
fixed, but you need to update your stix2extensions 

`pip install https://github.com/muchdogesec/stix2extensions/archive/main.zip`
